Neos:
  Flow:
    mvc:
      routes:
        'Neos.Neos':
          variables:
            'defaultUriSuffix': ''
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            options:
              variables:
                path: '404'

  Form:
    yamlPersistenceManager:
      savePath: 'resource://Liiioooo.DAProject/Private/Form/'
    presets:
      bootstrap:
        title: 'Bootstrap'
        parentPreset: default
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Liiioooo.DAProject/Private/Templates/ContactForm/{@type}.html'

  ContentRepository:
    contentDimensions:
      language:
        label: 'Language'
        icon: icon-language
        default: en
        defaultPreset: en
        presets:
          en:
            label: 'English'
            values:
              - en
            uriSegment: en
          de:
            label: 'German'
            values:
              - de
            uriSegment: de
