Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Neos.Demo:
            - Main
            - 'NodeTypes/*'

  ContentRepository:
    contentDimensions:
      language:
        label: 'Language'
        icon: icon-language
        default: en
        defaultPreset: en
        presets:
          en:
            label: 'English'
            values:
              - en
            uriSegment: en
          de:
            label: 'German'
            values:
              - de
            uriSegment: de
