Neos:
  Neos:
    nodeTypes:
      groups:
        section:
          position: 1
          label: 'Section'
    #      label: 'Neos.Neos:Main:nodeTypes.groups.structure'
          collapsed: false
        general:
          position: 2
          collapsed: true
        structure:
          collapsed: true
        plugins:
          collapsed: true
