Neos:
  Imagine:
    driver: Imagick
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: db
        user: db
        password: db
        host: db

    # The following is necessary to allow ddev to act as a proxy on your local machine
    http:
      trustedProxies:
        proxies: "*"
t3n:
  Neos:
    Debug:
      enabled: false      
      sql:
        # Set when a query should be considered as slow query. In ms
        slowQueryAfter: 10
