Neos:
  Imagine:
    driver: Imagick

  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: db
        user: db
        password: db
        host: 127.0.0.1

  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: '--'
        port: 'port'
        encryption: 'tls or ssl'
        username: '--'
        password: '--'
